Repository EnigmaticaModpacks/Enigmatica9, pull requests merged in 2022-10, with the labels that each got.

#48 Set up Loot Table functions for easily adding loot tables to mobs
  kubejs/server_scripts/base/loot_tables/entities/twilightforest/death_tome.js
  kubejs/server_scripts/functions.js
Labels: Development

#49 Occultism Custom Rituals
  config/jei/ingredient-list-mod-sort-order.ini
  config/jei/recipe-category-sort-order.ini
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/ritual_dummy.png
  kubejs/client_scripts/base/tooltips.js
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/server_scripts/base/entity/spawned/custom_rituals.js
  kubejs/server_scripts/constants/ritual_effects.js
  kubejs/server_scripts/expert/recipes/occultism/pentacles.js
  kubejs/server_scripts/expert/recipes/occultism/ritual.js
  kubejs/server_scripts/functions.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#51 helper tooltips, add missing lang entries for rituals
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/base/tooltips.js
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/server_scripts/constants/ritual_effects.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#53 Setup script to be able to disable ore gen
  kubejs/startup_scripts/worldgen_add.js
  kubejs/startup_scripts/worldgen_remove.js
Labels: Development

#52 Config Swapper - Setting up Quark
  config/configswapper/expert/config/blue_skies-common.toml
  config/configswapper/expert/config/naturesaura-common.toml
  config/configswapper/expert/config/quark-common.toml
  config/configswapper/expert/config/twilightforest-common.toml
  config/configswapper/normal/config/blue_skies-common.toml
  config/configswapper/normal/config/naturesaura-common.toml
  config/configswapper/normal/config/quark-common.toml
  config/configswapper/normal/config/twilightforest-common.toml
  kubejs/client_scripts/base/jei_descriptions.js
  kubejs/server_scripts/expert/gamerules/default.js
  kubejs/server_scripts/expert/tags/items/twilightforest/portal_activator.js
Labels: Development

#54 Set up basic NA recipe handlers
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/naturesaura/altar.js
  kubejs/server_scripts/expert/recipes/naturesaura/animal_spawner.js
  kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
Labels: Development

#55 Update ritual and entity summon scripts
  kubejs/server_scripts/base/entity/spawned/custom_rituals.js
  kubejs/server_scripts/expert/recipes/naturesaura/altar.js
  kubejs/server_scripts/functions.js
Labels: Development

#61 Revert Fairy Ring changes
  config/configswapper/expert/config/quark-common.toml
  config/configswapper/normal/config/quark-common.toml
Labels: Development

#62 Cleanup string validation on scripts
  kubejs/server_scripts/expert/recipes/immersiveengineering/blastfurnace_fuel.js
  kubejs/server_scripts/expert/recipes/naturesaura/altar.js
  kubejs/server_scripts/expert/recipes/naturesaura/animal_spawner.js
  kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
  kubejs/server_scripts/expert/recipes/occultism/ritual.js
Labels: Development

#63 [Expert] Disable Blue Skies portals
  kubejs/client_scripts/expert/jei_descriptions.js
  kubejs/server_scripts/expert/block_events/disable_blueskies_portals.js
Labels: Development

#64 add description to zeal lighter too
  kubejs/client_scripts/expert/jei_descriptions.js
Labels: Development

#66 Fix Twilight Forest portal
  kubejs/server_scripts/expert/tags/items/twilightforest/portal_activator.js
Labels: Bug

#68 [Expert] Lychee test scripts and examples
  kubejs/server_scripts/constants/no_despawn.js
  kubejs/server_scripts/expert/entity_events/spawned/no_despawn.js
  kubejs/server_scripts/expert/recipes/lychee/item_inside.js
  kubejs/server_scripts/expert/recipes/lychee/lightning_channeling.js
  kubejs/server_scripts/expert/tags/items/lychee/fire_immune.js
Labels: Development

#70 [expert] cleaner lychee recipe view, lang files for condition descriptions
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/expert/recipes/lychee/item_inside.js
Labels: Development

#34 Quest Port from E8
  .gitignore
  config/ftbquests/quests/chapter_groups.snbt
  config/ftbquests/quests/chapters/adventure.snbt
  config/ftbquests/quests/chapters/applied_energistics_2.snbt
  config/ftbquests/quests/chapters/applied_energistics_2_wip.snbt
  config/ftbquests/quests/chapters/ars_nouveau.snbt
  config/ftbquests/quests/chapters/automation.snbt
  config/ftbquests/quests/chapters/blood_magic_wip.snbt
  config/ftbquests/quests/chapters/botania.snbt
  config/ftbquests/quests/chapters/building.snbt
  config/ftbquests/quests/chapters/challenges.snbt
  config/ftbquests/quests/chapters/create.snbt
  config/ftbquests/quests/chapters/getting_started.snbt
  config/ftbquests/quests/chapters/hidden_quests.snbt
  config/ftbquests/quests/chapters/immersive_engineering.snbt
  config/ftbquests/quests/chapters/industrial_foregoing.snbt
  config/ftbquests/quests/chapters/mekanism.snbt
  config/ftbquests/quests/chapters/natures_aura.snbt
  config/ftbquests/quests/chapters/occultism.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  config/ftbquests/quests/chapters/powah.snbt
  config/ftbquests/quests/chapters/rftools_wip.snbt
  config/ftbquests/quests/chapters/storage.snbt
  config/ftbquests/quests/chapters/thermal_series.snbt
  config/ftbquests/quests/chapters/tinkers_construct.snbt
  config/ftbquests/quests/chapters/tools.snbt
  config/ftbquests/quests/data.snbt
  kubejs/assets/enigmatica/textures/quests_icons/moose_headgear.png
  kubejs/assets/enigmatica/textures/quests_icons/night_vision_goggles.png
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_alchemists_delight.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_ars_nouveau_loot_rare.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_blacksmiths_delight.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_create_loot_epic.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_create_loot_legendary.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_create_loot_rare.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_farmers_delight.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_immersive_engineering_loot_epic.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_immersive_engineering_loot_rare.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_mekanism_loot_epic.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_mekanism_loot_legendary.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_mekanism_loot_rare.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_miners_delight.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_natures_aura_loot_epic.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_natures_aura_loot_rare.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_occultism_loot_epic.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_occultism_loot_legendary.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_pneumaticcraft_loot_epic.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_pneumaticcraft_loot_legendary.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_pneumaticcraft_loot_rare.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_powah_loot.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_rftools_loot_rare.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_scavengers_delight.json
  kubejs/data/enigmatica/loot_tables/loot_boxes/quest_sorcerers_delight.json
  kubejs/server_scripts/base/recipes/eccentrictome/shapeless.js
  kubejs/server_scripts/base/tags/items/enigmatica/storage/basic.js
  kubejs/server_scripts/base/tags/items/enigmatica/storage/bulk.js
  kubejs/server_scripts/base/tags/items/enigmatica/storage/energy.js
  kubejs/server_scripts/base/tags/items/enigmatica/storage/gases.js
  kubejs/server_scripts/base/tags/items/enigmatica/weapons/melee.js
Labels: Enhancement

#83 Yeet extra ae2 quest chapter
  config/ftbquests/quests/chapters/applied_energistics_2_wip.snbt
Labels: Development

#84 rename bm chapter
  config/ftbquests/quests/chapters/blood_magic.snbt
Labels: Development

#85 rename rftools chapter
  config/ftbquests/quests/chapters/rftools.snbt
Labels: Development

#86 Update Storage quests
  config/ftbquests/quests/chapters/storage.snbt
Labels: Development

#87 adventure quest updates, cleanup
  config/ftbquests/quests/chapters/adventure.snbt
  config/ftbquests/quests/chapters/applied_energistics_2.snbt
  config/ftbquests/quests/chapters/blood_magic.snbt
  config/ftbquests/quests/chapters/challenges.snbt
  config/ftbquests/quests/chapters/rftools.snbt
Labels: Development

#88 Add Storage Controller quest
  config/ftbquests/quests/chapters/storage.snbt
Labels: Development

#90 Ars Nouveau Quest Refresh
  config/ftbquests/quests/chapters/ars_nouveau.snbt
Labels: Enhancement

#91 Nature's Aura Quest Refresh
  config/ftbquests/quests/chapters/natures_aura.snbt
  config/ftbquests/quests/chapters/tools.snbt
  kubejs/assets/ae2/textures/block/controller_column_lights.png.mcmeta
  kubejs/assets/ae2/textures/block/controller_lights.png.mcmeta
  kubejs/assets/ae2/textures/block/molecular_assembler_lights.png.mcmeta
  kubejs/client_scripts/base/tooltips.js
Labels: Enhancement

#98 updates for new KubeJS version
  kubejs/server_scripts/functions.js
  kubejs/server_scripts/settings.js
Labels: Development

#92 PneumaticCraft Quest refresh
  config/ftbquests/quests/chapters/hidden_quests.snbt
  config/ftbquests/quests/chapters/natures_aura.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  config/ftbquests/quests/chapters/tools.snbt
  config/patchouli-client.toml
  kubejs/config/common.properties
Labels: Enhancement

#104 Update tooltips.js
  kubejs/client_scripts/base/tooltips.js
Labels: Development

#105 missed a few descriptions in PNC quests
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
Labels: Development

#109 fix dependencies in mek quests
  config/ftbquests/quests/chapters/mekanism.snbt
Labels: Development

#110 clean up health boost on equipped mobs
  kubejs/server_scripts/base/entity/spawned/equipment.js
Labels: Development
