Repository EnigmaticaModpacks/Enigmatica9, pull requests merged in 2023-06, with the labels that each got.

#363 Fix some small various things
  .gitattributes
  .gitignore
  config/emendatusenigmatica/material/andesite_alloy.json
  config/emendatusenigmatica/material/charcoal.json
  config/emendatusenigmatica/material/dimensional.json
  kubejs/assets/emendatusenigmatica/lang/en_us.json
  kubejs/client_scripts/base/jei_ee_conversion_note.js
  kubejs/server_scripts/base/recipes/create/haunting.js
  kubejs/server_scripts/base/recipes/enigmatica/remove.js
  kubejs/server_scripts/base/tags/items/create/crushed_ores.js
  kubejs/server_scripts/base/unification/unify_loot.js
  kubejs/server_scripts/normal/unification/unify_dust_processing.js
Labels: Bug

#370 Replace EE Gold Nugget to Vanilla one in the Thermal Netherite Processing Recipe
  kubejs/server_scripts/normal/recipes/thermal/smelter.js
Labels: Enhancement

#372 config refresh to 'normal'
  config/Mekanism/gear.toml
  config/Mekanism/machine-usage.toml
  config/Mekanism/tiers.toml
  config/apotheosis/adventure.cfg
  config/apotheosis/enchantments.cfg
  config/ars_elemental/glyph_curved_projectile.toml
  config/ars_elemental/glyph_discharge.toml
  config/ars_elemental/glyph_homing_projectile.toml
  config/ars_nouveau/glyph_break.toml
  config/ars_nouveau/glyph_crush.toml
  config/entangled-common.toml
  config/industrialforegoing/machine-resource-production.toml
  config/mininggadgets-common.toml
  config/modularrouters-common.toml
  config/naturesaura-common.toml
  config/pneumaticcraft-common.toml
  config/quark-common.toml
  config/restrictedportals-common.toml
  config/twilightforest-common.toml
  kubejs/assets/create/lang/en_us.json
  kubejs/assets/emendatusenigmatica/lang/en_us.json
  kubejs/assets/pneumaticcraft/lang/en_us.json
  kubejs/client_scripts/lang_modifications.js
  kubejs/data/immersiveengineering/structures/multiblocks/sheetmetal_tank.nbt
  kubejs/data/immersiveengineering/structures/multiblocks/silo.nbt
  kubejs/data/immersiveengineering/structures/multiblocks/squeezer.nbt
Labels: Development

#382 quick fix for lack of andesite in twilight forest
  kubejs/server_scripts/expert/recipes/hexerei/shaped.js
  kubejs/server_scripts/expert/recipes/minecraft/shaped.js
Labels: Development

#386 reduce cost of fell, add magic map to starting gear
  config/configswapper/expert/config/ars_nouveau/glyph_fell.toml
  kubejs/server_scripts/expert/player_events/starting_items.js
Labels: Development

#388 Expert Playtest feedback fixes
  config/configswapper/expert/config/emendatusenigmatica/material/gold.json
  config/configswapper/normal/config/emendatusenigmatica/material/gold.json
  config/ftbquests/quests/chapters/chapter_one.snbt
  kubejs/client_scripts/base/jei_descriptions.js
  kubejs/server_scripts/base/tags/blocks/ars_nouveau/gravity_blacklist.js
  kubejs/server_scripts/base/tags/blocks/ars_nouveau/whirlisprig.js
  kubejs/server_scripts/expert/recipes/enigmatica/crushing_tiers.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/enigmatica/replace_input.js
  kubejs/server_scripts/expert/recipes/hexerei/mixingcauldron.js
  kubejs/server_scripts/expert/recipes/twilightforest/hollow_hills.js
Labels: Development

#389 correcting issues with mortar and pestle processing
  kubejs/client_scripts/lang_modifications.js
  kubejs/server_scripts/expert/recipes/enigmatica/crushing_tiers.js
Labels: Development

#391 E9E Feedback
  kubejs/assets/ars_nouveau/lang/en_us.json
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/nomadictents/shaped.js
Labels: Development

#394 Expert Tweaks
  config/configswapper/expert/config/naturesaura-common.toml
  config/configswapper/expert/config/quark-common.toml
  config/ftbquests/quests/chapters/chapter_one.snbt
  kubejs/assets/simplytools/lang/en_us.json
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/client_scripts/lang_modifications.js
  kubejs/server_scripts/base/loot_tables/blocks/minecraft/spawner.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/basement.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/foundation_basement.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/useless.js
  kubejs/server_scripts/base/recipes/apotheosis/bosses/twilight_forest.js
  kubejs/server_scripts/base/recipes/gateways/gateways.js
  kubejs/server_scripts/base/recipes/minecraft/shapeless.js
  kubejs/server_scripts/base/recipes/naturesaura/animal_spawner.js
  kubejs/server_scripts/base/recipes/thermal/chiller.js
  kubejs/server_scripts/base/tags/fluids/forge/tallow.js
  kubejs/server_scripts/base/tags/items/forge/lights.js
  kubejs/server_scripts/base/tags/items/minecraft/candles.js
  kubejs/server_scripts/expert/loot_tables/blocks/minecraft/spawner.js
  kubejs/server_scripts/expert/recipes/apotheosis/bosses/twilight_forest.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/enigmatica/replace_input.js
  kubejs/server_scripts/expert/recipes/hexerei/mixingcauldron.js
  kubejs/server_scripts/expert/recipes/minecraft/shaped.js
  kubejs/server_scripts/expert/recipes/naturesaura/altar.js
  kubejs/server_scripts/expert/recipes/naturesaura/animal_spawner.js
  kubejs/server_scripts/expert/recipes/naturesaura/patchouli_safe_remove.js
  kubejs/server_scripts/expert/recipes/naturesaura/shaped.js
  kubejs/server_scripts/expert/recipes/toolbelt/shaped.js
  kubejs/server_scripts/normal/loot_tables/blocks/minecraft/spawner.js
  kubejs/server_scripts/normal/recipes/apotheosis/bosses/twilight_forest.js
Labels: Development

#395 Expert random glyph reward fix
  config/ftbquests/quests/chapters/chapter_one.snbt
Labels: Development

#396 Increase drop rate of saplings from quark trees
  changelogs/CHANGELOG.md
  kubejs/server_scripts/base/loot_tables/blocks/quark/blossom_leaves.js
Labels: Enhancement

#398 Expert feedback adjustments
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/getting_started.snbt
  config/ftbquests/quests/chapters/immersive_engineering_expert.snbt
  config/ftbquests/quests/chapters/natures_aura_expert.snbt
  kubejs/assets/minecraft/lang/en_us.json
  kubejs/client_scripts/lang_modifications.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/natures_aura_loot_boxes.js
  kubejs/server_scripts/base/recipes/twilightforest/stalactites.js
  kubejs/server_scripts/base/tags/items/forge/glyphs.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/natures_aura_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/entities/twilightforest/naga.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/shapeless.js
  kubejs/server_scripts/expert/recipes/naturesaura/altar.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/shaped.js
  kubejs/server_scripts/expert/recipes/twilightforest/hollow_hills.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/natures_aura_loot_boxes.js
Labels: Development

#402 Update CHANGELOG.md
  changelogs/CHANGELOG.md
Labels: Development

#403 Add recipes for obtaining Niter from Sandstone
  changelogs/CHANGELOG.md
  kubejs/server_scripts/base/recipes/ars_nouveau/crushing.js
  kubejs/server_scripts/base/recipes/create/crushing.js
  kubejs/server_scripts/base/recipes/create/milling.js
  kubejs/server_scripts/base/recipes/enigmatica/remove.js
  kubejs/server_scripts/base/recipes/immersiveengineering/crusher.js
  kubejs/server_scripts/base/recipes/thermal/pulverizer.js
  kubejs/server_scripts/base/tags/items/forge/sandstone.js
  kubejs/server_scripts/constants/colors.js
Labels: Enhancement

#405 E9E feedback tweaks
  config/almostunified/unify.json
  config/configswapper/expert/config/ars_nouveau/glyph_break.toml
  config/ftbquests/quests/chapters/create_expert.snbt
  config/ftbquests/quests/chapters/immersive_engineering_expert.snbt
  config/ftbquests/quests/chapters/industrial_foregoing_expert.snbt
  config/ftbquests/quests/chapters/mekanism_expert.snbt
  config/ftbquests/quests/chapters/thermal_series_expert.snbt
  kubejs/client_scripts/base/tooltips.js
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/client_scripts/expert/tooltips.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/mekanism_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/idas/necromancers_spire/necromancers_spire.js
  kubejs/server_scripts/base/loot_tables/chests/idas/witches_treestump/witches_treestump.js
  kubejs/server_scripts/base/loot_tables/chests/minecraft/bastion_other.js
  kubejs/server_scripts/base/loot_tables/chests/minecraft/bastion_treasure.js
  kubejs/server_scripts/base/loot_tables/chests/minecraft/desert_pyramid.js
  kubejs/server_scripts/base/loot_tables/chests/minecraft/end_city_treasure.js
  kubejs/server_scripts/base/loot_tables/chests/minecraft/jungle_temple.js
  kubejs/server_scripts/base/loot_tables/chests/minecraft/shipwreck.js
  kubejs/server_scripts/base/loot_tables/chests/minecraft/simple_dungeon.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/darktower_cache.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/fancy_well.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/hill_1.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/hill_2.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/hill_3.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/well.js
  kubejs/server_scripts/base/recipes/farmersdelight/cutting.js
  kubejs/server_scripts/base/unification/unify_loot.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/mekanism_loot_boxes.js
  kubejs/server_scripts/expert/recipes/ae2/shaped.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/imbuement.js
  kubejs/server_scripts/expert/recipes/create/shaped.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/manyideas/shaped.js
  kubejs/server_scripts/expert/recipes/mekanism/shaped.js
  kubejs/server_scripts/expert/recipes/minecraft/shaped.js
  kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/mekanism_loot_boxes.js
Labels: Development

#406 tooltip update
  kubejs/client_scripts/base/tooltips.js
Labels: Development

#407 Expert Adjustments
  kubejs/server_scripts/base/unification/unify_loot.js
  kubejs/server_scripts/expert/recipes/ae2/shaped.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/shapeless.js
  kubejs/server_scripts/expert/recipes/farmersdelight/cutting.js
Labels: Development

#409 Fix Powah Reactor recipe
  changelogs/CHANGELOG.md
  kubejs/server_scripts/normal/recipes/powah/shaped.js
Labels: Enhancement

#410 Buff Occultism and Hexerei Combat Familiars
  changelogs/CHANGELOG.md
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/hexerei.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/occultism.js
Labels: Enhancement

#412 Fix for unobtainable nickel
  kubejs/server_scripts/base/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/create/filling.js
  kubejs/server_scripts/expert/recipes/create/mixing.js
  kubejs/server_scripts/expert/recipes/enigmatica/blasting.js
  kubejs/server_scripts/expert/recipes/enigmatica/crushing_tiers.js
  kubejs/server_scripts/expert/recipes/immersiveengineering/bottling_machine.js
  kubejs/server_scripts/expert/recipes/thermal/bottler.js
Labels: Development

#413 E9e feedback changes
  changelogs/CHANGELOG.md
  config/configswapper/expert/config/apotheosis/enchantments.cfg
  config/configswapper/normal/config/apotheosis/enchantments.cfg
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/create_expert.snbt
  config/ftbquests/quests/chapters/thermal_series.snbt
  config/ftbquests/quests/chapters/thermal_series_expert.snbt
  config/ftbquests/quests/chapters/tools.snbt
  config/ftbquests/quests/chapters/tools_expert.snbt
  kubejs/client_scripts/base/tooltips.js
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/hexerei.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/occultism.js
  kubejs/server_scripts/base/recipes/ars_nouveau/shapeless.js
  kubejs/server_scripts/base/recipes/createaddition/rolling.js
  kubejs/server_scripts/base/recipes/enigmatica/remove.js
  kubejs/server_scripts/base/recipes/farmersdelight/cutting.js
  kubejs/server_scripts/base/recipes/immersiveengineering/metalpress.js
  kubejs/server_scripts/base/recipes/thermal/press.js
  kubejs/server_scripts/base/recipes/twilightforest/shapeless.js
  kubejs/server_scripts/constants/gem_properties.js
  kubejs/server_scripts/constants/metal_properties.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/natures_aura_loot_boxes.js
  kubejs/server_scripts/expert/recipes/ae2/shaped.js
  kubejs/server_scripts/expert/recipes/apotheosis/shaped.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/glyph.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/imbuement.js
  kubejs/server_scripts/expert/recipes/create/mixing.js
  kubejs/server_scripts/expert/recipes/farmersdelight/cutting.js
  kubejs/server_scripts/expert/recipes/hexerei/mixingcauldron.js
  kubejs/server_scripts/expert/recipes/minecraft/shaped.js
  kubejs/server_scripts/expert/recipes/thermal/shaped.js
  kubejs/server_scripts/normal/recipes/immersiveengineering/metalpress.js
  kubejs/server_scripts/normal/recipes/immersiveengineering/shaped.js
  kubejs/server_scripts/normal/recipes/thermal/press.js
Labels: Development

#415 E9E feedback
  changelogs/CHANGELOG.md
  config/configswapper/expert/config/emendatusenigmatica/material/silver.json
  config/configswapper/normal/config/emendatusenigmatica/material/silver.json
  config/ftbquests/quests/chapters/ars_nouveau.snbt
  config/ftbquests/quests/chapters/ars_nouveau_expert.snbt
  config/ftbquests/quests/chapters/building.snbt
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/create.snbt
  config/ftbquests/quests/chapters/create_expert.snbt
  kubejs/client_scripts/lang_modifications.js
  kubejs/server_scripts/base/loot_tables/chests/twilightforest/tree_cache.js
  kubejs/server_scripts/base/recipes/enigmatica/remove.js
  kubejs/server_scripts/base/recipes/powah/shaped.js
  kubejs/server_scripts/base/recipes/twilightforest/shaped.js
  kubejs/server_scripts/base/recipes/twilightforest/shapeless.js
  kubejs/server_scripts/constants/cobbleworks.js
  kubejs/server_scripts/constants/dye_sources.js
  kubejs/server_scripts/expert/loot_tables/entities/twilightforest/death_tome.js
  kubejs/server_scripts/expert/recipes/hexerei/mixingcauldron.js
  kubejs/server_scripts/expert/recipes/immersiveengineering/shaped.js
  kubejs/server_scripts/expert/recipes/industrialforegoing/dissolution_chamber.js
  kubejs/server_scripts/expert/recipes/industrialforegoing/shaped.js
  kubejs/server_scripts/expert/recipes/naturesaura/altar.js
  kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
Labels: Development

#419 Disable Potion Particles
  kubejs/assets/minecraft/textures/particle/effect_0.png
  kubejs/assets/minecraft/textures/particle/effect_1.png
  kubejs/assets/minecraft/textures/particle/effect_2.png
  kubejs/assets/minecraft/textures/particle/effect_3.png
  kubejs/assets/minecraft/textures/particle/effect_4.png
  kubejs/assets/minecraft/textures/particle/effect_5.png
  kubejs/assets/minecraft/textures/particle/effect_6.png
  kubejs/assets/minecraft/textures/particle/effect_7.png
Labels: Enhancement

#420 e9e feedback continued
  config/configswapper/expert/config/trofers-common.toml
  config/configswapper/normal/config/trofers-common.toml
  defaultconfigs/clienttweaks-common.toml
  kubejs/assets/minecraft/textures/particle/effect_0.png
  kubejs/assets/minecraft/textures/particle/effect_1.png
  kubejs/assets/minecraft/textures/particle/effect_2.png
  kubejs/assets/minecraft/textures/particle/effect_3.png
  kubejs/assets/minecraft/textures/particle/effect_4.png
  kubejs/assets/minecraft/textures/particle/effect_5.png
  kubejs/assets/minecraft/textures/particle/effect_6.png
  kubejs/assets/minecraft/textures/particle/effect_7.png
  kubejs/server_scripts/base/tags/items/forge/rods.js
  kubejs/server_scripts/expert/recipes/ae2/shaped.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/expert/recipes/create/mixing.js
  kubejs/server_scripts/expert/recipes/functionalstorage/shaped.js
  kubejs/server_scripts/expert/recipes/immersiveengineering/shaped.js
  kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/shaped.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/thermo_plant.js
  kubejs/server_scripts/expert/recipes/sophisticatedstorage/shaped.js
  kubejs/server_scripts/expert/recipes/thermal/smelter.js
Labels: Development

#421 Moar e9e feedback changes
  config/ftbquests/quests/chapters/chapter_one.snbt
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/minecraft.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/thermal.js
  kubejs/server_scripts/base/tags/entity_type/friendlyfire/general_protection.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/shaped.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/shapeless.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/thermo_plant.js
Labels: Development

#422 e9e feedback
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/powah_expert.snbt
  kubejs/client_scripts/lang_modifications.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/ars_nouveau.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/cnb.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/hexerei.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/minecraft.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/occultism.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/thermal.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/twilightforest.js
  kubejs/server_scripts/constants/metal_properties.js
  kubejs/server_scripts/constants/minibosses.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/hexerei/mixingcauldron.js
  kubejs/server_scripts/expert/recipes/modularrouters/shaped.js
  kubejs/server_scripts/expert/recipes/powah/shaped.js
  kubejs/server_scripts/expert/recipes/thermal/shaped.js
  kubejs/server_scripts/expert/recipes/thermal/smelter.js
Labels: Development

#423 E9E Feedback
  kubejs/server_scripts/base/recipes/thermal/brewer.js
  kubejs/server_scripts/base/recipes/thermal/centrifuge.js
  kubejs/server_scripts/base/recipes/thermal/crucible.js
  kubejs/server_scripts/base/recipes/thermal/crystallizer.js
  kubejs/server_scripts/base/recipes/thermal/insolator.js
  kubejs/server_scripts/base/recipes/thermal/press.js
  kubejs/server_scripts/base/recipes/thermal/pulverizer.js
  kubejs/server_scripts/base/recipes/thermal/pyrolyzer.js
  kubejs/server_scripts/base/recipes/thermal/sawmill.js
Labels: Development

#424 E9E Feedback
  config/ftbquests/quests/chapters/powah_expert.snbt
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/ae2_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/ars_nouveau_glyph_cache.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/ars_nouveau_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/create_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/hexerei_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/immersive_engineering_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/industrial_foregoing_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/occultism_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/pneumaticcraft_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/powah_loot_boxes.js
  kubejs/server_scripts/base/loot_tables/chests/enigmatica/thermal_series_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/ae2_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/ars_nouveau_glyph_cache.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/ars_nouveau_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/create_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/delight_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/hexerei_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/immersive_engineering_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/industrial_foregoing_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/occultism_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/pneumaticcraft_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/powah_loot_boxes.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/thermal_series_loot_boxes.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/assembly.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/ae2_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/ars_nouveau_glyph_cache.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/ars_nouveau_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/create_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/delight_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/hexerei_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/immersive_engineering_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/industrial_foregoing_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/occultism_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/pneumaticcraft_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/powah_loot_boxes.js
  kubejs/server_scripts/normal/loot_tables/chests/enigmatica/thermal_series_loot_boxes.js
Labels: Development

#425 E9E Feedback Fixes
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/chapter_two.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/server_scripts/base/recipes/apotheosis/miniboss_gear/skeleton.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/minecraft.js
  kubejs/server_scripts/base/tags/blocks/ars_nouveau/break_blacklist.js
  kubejs/server_scripts/base/tags/blocks/ars_nouveau/gravity_blacklist.js
  kubejs/server_scripts/base/tags/items/ars_nouveau/golem.js
  kubejs/server_scripts/constants/ritual_effects.js
  kubejs/server_scripts/expert/loot_tables/entities/twilightforest/darktower_boss.js
  kubejs/server_scripts/expert/recipes/apotheosis/potion_charm.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/armor_upgrade.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/imbuement.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/shaped.js
  kubejs/server_scripts/expert/recipes/createaddition/charging.js
  kubejs/server_scripts/expert/recipes/mekanism/metallurgic_infusing.js
  kubejs/server_scripts/expert/recipes/naturesaura/altar.js
  kubejs/server_scripts/expert/recipes/occultism/ritual.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/assembly.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#431 Potion adjustments
  config/ftbquests/quests/chapters/ars_nouveau_expert.snbt
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/chapter_two.snbt
  config/ftbquests/quests/chapters/mekanism_expert.snbt
  config/ftbquests/quests/chapters/natures_aura_expert.snbt
  config/ftbquests/quests/chapters/occultism_expert.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized_expert.snbt
  config/ftbquests/quests/chapters/powah_expert.snbt
  kubejs/client_scripts/base/jei_descriptions.js
  kubejs/server_scripts/base/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/book_upgrade.js
  kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
Labels: Development

#432 Fix Animal Fat Drops
  changelogs/CHANGELOG.md
  kubejs/server_scripts/base/loot_modifiers/hexerei/remove.js
  kubejs/server_scripts/base/loot_tables/entities/hexerei/animal_fat.js
Labels: Enhancement

#433 Expert Updates
  config/ftbquests/quests/chapter_groups.snbt
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/chapter_two.snbt
  config/ftbquests/quests/chapters/tinkers_construct.snbt
  config/lootr-common.toml
  config/the_bumblezone/general.toml
  kubejs/client_scripts/expert/jei_descriptions.js
  kubejs/server_scripts/base/loot_tables/blocks/quark/ancient_leaves.js
  kubejs/server_scripts/base/tags/blocks/ars_nouveau/whirlisprig.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/delight_loot_boxes.js
  kubejs/server_scripts/expert/player_events/armor_sets.js
  kubejs/server_scripts/expert/recipes/apotheosis/potion_charm.js
  kubejs/server_scripts/expert/recipes/farmersdelight/shaped.js
  kubejs/server_scripts/expert/recipes/occultism/ritual.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/expert/recipes/starbunclemania/shaped.js
  kubejs/server_scripts/expert/recipes/the_bumblezone/armor_upgrade.js
  kubejs/server_scripts/expert/recipes/thermal/shaped.js
Labels: Development

#434 E9E Feedback Adjustments
  config/ftbquests/quests/chapters/applied_energistics_2_expert.snbt
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/chapter_three.snbt
  config/ftbquests/quests/chapters/chapter_two.snbt
  config/ftbquests/quests/chapters/create_expert.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized.snbt
  config/ftbquests/quests/chapters/pneumaticcraft_repressurized_expert.snbt
  config/ftbquests/quests/chapters/villagers.snbt
  config/ftbquests/quests/chapters/villagers_expert.snbt
  kubejs/client_scripts/base/jei_add_items.js
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/expert/recipes/create/mechanical_crafting.js
  kubejs/server_scripts/expert/recipes/create/shaped.js
  kubejs/server_scripts/expert/recipes/energymeter/shaped.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/immersiveengineering/shapeless.js
  kubejs/server_scripts/expert/recipes/industrialforegoing/laser_drill_fluid.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/assembly.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/heat_frame_cooling.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/shaped.js
  kubejs/server_scripts/expert/recipes/thermal/smelter.js
Labels: Development

#435 E9E Feedback Changes
  config/ars_nouveau/glyph_aoe.toml
  config/configswapper/expert/config/ars_nouveau/glyph_aoe.toml
  config/configswapper/expert/config/ars_nouveau/glyph_blink.toml
  config/ftbquests/quests/chapters/ars_nouveau.snbt
  config/ftbquests/quests/chapters/ars_nouveau_expert.snbt
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/chapter_two.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/server_scripts/base/gamerules/default.js
  kubejs/server_scripts/base/recipes/apotheosis/miniboss_gear/wild_hunt.js
  kubejs/server_scripts/base/recipes/gateways/gateways.js
  kubejs/server_scripts/base/tags/blocks/mekanism/cardboard_blacklist.js
  kubejs/server_scripts/expert/loot_tables/entities/twilightforest/death_tome.js
  kubejs/server_scripts/expert/player_events/starting_items.js
  kubejs/server_scripts/expert/recipes/create/compacting.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/immersiveengineering/squeezer.js
  kubejs/server_scripts/expert/recipes/occultism/ritual.js
  kubejs/server_scripts/expert/recipes/theurgy/shaped.js
Labels: Development

#436 E9E Feedback
  changelogs/CHANGELOG.md
  config/configswapper/expert/config/ars_nouveau-common.toml
  config/configswapper/expert/config/quark-common.toml
  config/configswapper/expert/serverconfig/create-server.toml
  config/configswapper/expert/serverconfig/xnet-server.toml
  config/configswapper/normal/config/ars_nouveau-common.toml
  config/configswapper/normal/config/quark-common.toml
  config/ftbquests/quests/chapters/chapter_one.snbt
  config/ftbquests/quests/chapters/chapter_two.snbt
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/server_scripts/base/loot_tables/blocks/minecraft/oak_leaves.js
  kubejs/server_scripts/base/recipes/enigmatica/remove.js
  kubejs/server_scripts/base/tags/items/curios/bundle.js
  kubejs/server_scripts/constants/ritual_effects.js
  kubejs/server_scripts/expert/recipes/create/shaped.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/occultism/ritual.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/shaped.js
Labels: Development

#438 E9E tweaks
  config/configswapper/expert/config/entangled-common.toml
  config/configswapper/expert/serverconfig/enigmaticunity-server.toml
  config/configswapper/normal/config/entangled-common.toml
  config/ftbquests/quests/chapters/ars_nouveau_expert.snbt
  config/ftbquests/quests/chapters/chapter_three.snbt
  config/ftbquests/quests/chapters/chapter_two.snbt
  kubejs/assets/kubejs/textures/item/drillhead_steel.png
  kubejs/assets/kubejs/textures/item/sawblade.png
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/client_scripts/expert/textures.js
  kubejs/client_scripts/lang_modifications.js
  kubejs/server_scripts/base/block_events/clear_weather.js
  kubejs/server_scripts/base/recipes/lychee/block_interacting.js
  kubejs/server_scripts/base/tags/blocks/ars_nouveau/harvest.js
  kubejs/server_scripts/expert/advancements/the_bumblezone.js
  kubejs/server_scripts/expert/recipes/create/item_application.js
  kubejs/server_scripts/expert/recipes/create/mixing.js
  kubejs/server_scripts/expert/recipes/create/sequenced_assembly.js
  kubejs/server_scripts/expert/recipes/create/shaped.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/immersiveengineering/shaped.js
  kubejs/server_scripts/expert/recipes/minecraft/shaped.js
  kubejs/server_scripts/expert/recipes/occultism/ritual.js
  kubejs/server_scripts/expert/recipes/railways/shaped.js
  kubejs/server_scripts/expert/villager_trades/immersiveengineering/electrician.js
  kubejs/server_scripts/expert/villager_trades/pneumaticcraft/mechanic.js
Labels: Development

#440 E9E Testing - Continued Feedback
  config/ftbquests/quests/chapters/create.snbt
  config/ftbquests/quests/chapters/create_expert.snbt
  config/ftbquests/quests/chapters/occultism_expert.snbt
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/client_scripts/base/jei_descriptions.js
  kubejs/server_scripts/base/recipes/apotheosis/minibosses/minecraft.js
  kubejs/server_scripts/base/tags/entity_type/enigmatica/mob_spawner_blacklist.js
  kubejs/server_scripts/base/tags/entity_type/spirit/collect_blacklisted.js
  kubejs/server_scripts/base/tags/items/forge/rods.js
  kubejs/server_scripts/expert/loot_tables/chests/enigmatica/natures_aura_loot_boxes.js
  kubejs/server_scripts/expert/recipes/create/shaped.js
  kubejs/server_scripts/expert/recipes/hexerei/pestle_and_mortar.js
  kubejs/server_scripts/expert/recipes/naturesaura/altar.js
  kubejs/server_scripts/expert/recipes/twilightforest/shaped.js
Labels: Development

#445 E9E continued feedback
  config/clienttweaks-common.toml
  kubejs/assets/kubejs/lang/en_us.json
  kubejs/assets/kubejs/textures/item/shears.png
  kubejs/client_scripts/expert/textures.js
  kubejs/client_scripts/lang_modifications.js
  kubejs/server_scripts/base/block_events/clear_weather.js
  kubejs/server_scripts/base/recipes/createaddition/liquid_burning.js
  kubejs/server_scripts/base/recipes/immersiveengineering/generator_fuel.js
  kubejs/server_scripts/base/recipes/pneumaticcraft/fuel_quality.js
  kubejs/server_scripts/base/recipes/thermal/fuel/compression.js
  kubejs/server_scripts/base/recipes/twilightforest/shaped.js
  kubejs/server_scripts/base/tags/fluids/create/bottomless_allow.js
  kubejs/server_scripts/constants/fuel_properties.js
  kubejs/server_scripts/expert/recipes/createaddition/liquid_burning.js
  kubejs/server_scripts/expert/recipes/immersiveengineering/generator_fuel.js
  kubejs/server_scripts/expert/recipes/lychee/block_interacting.js
  kubejs/server_scripts/expert/recipes/minecraft/shaped.js
  kubejs/server_scripts/expert/recipes/occultism/ritual.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/fuel_quality.js
  kubejs/server_scripts/expert/recipes/redstonepen/shaped.js
  kubejs/server_scripts/expert/recipes/thermal/fuel/compression.js
  kubejs/server_scripts/normal/recipes/createaddition/liquid_burning.js
  kubejs/server_scripts/normal/recipes/immersiveengineering/generator_fuel.js
  kubejs/server_scripts/normal/recipes/pneumaticcraft/fuel_quality.js
  kubejs/server_scripts/normal/recipes/thermal/fuel/compression.js
  kubejs/server_scripts/normal/tags/fluids/create/bottomless_allow.js
  kubejs/startup_scripts/item_registry.js
Labels: Development

#446 recipe conflicts fixes
  changelogs/CHANGELOG.md
  config/almostunified/unify.json
  config/configswapper/expert/config/quark-common.toml
  config/configswapper/normal/config/quark-common.toml
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/server_scripts/base/loot_tables/blocks/densetrees/dense_logs.js
  kubejs/server_scripts/base/recipes/byg/shaped.js
  kubejs/server_scripts/base/recipes/enigmatica/remove.js
  kubejs/server_scripts/base/recipes/enigmatica/shapeless.js
  kubejs/server_scripts/base/recipes/minecraft/shapeless.js
  kubejs/server_scripts/base/recipes/minecraft/stonecutting.js
  kubejs/server_scripts/base/recipes/naturesaura/shaped.js
  kubejs/server_scripts/base/recipes/supplementaries/shaped.js
  kubejs/server_scripts/base/tags/blocks/forge/storage_blocks.js
  kubejs/server_scripts/base/tags/items/forge/storage_blocks.js
Labels: Enhancement

#447 E9E Feedback
  config/ftbquests/quests/chapters/chapter_one.snbt
  kubejs/server_scripts/base/block_events/clear_weather.js
  kubejs/server_scripts/expert/loot_tables/entities/twilightforest/snow_queen.js
  kubejs/server_scripts/expert/recipes/ae2/shaped.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/modularrouters/shaped.js
  kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/shaped.js
Labels: Development
