Repository EnigmaticaModpacks/Enigmatica9, pull requests merged in 2023-04, with the labels that each got.

#287 Add quests detailing the new Ars Nouveau Bookwyrm Storage System
  config/ftbquests/quests/chapters/ars_nouveau.snbt
  kubejs/client_scripts/base/tooltips.js
Labels: Enhancement

#291 Ars Quest clarification
  config/ftbquests/quests/chapters/ars_nouveau.snbt
Labels: Enhancement

#305 Rebalance Enigmatic Unity power conversion
  config/configswapper/expert/serverconfig/enigmaticunity-server.toml
  config/configswapper/normal/serverconfig/enigmaticunity-server.toml
Labels: Enhancement

#306 Make Demon's Dream, Hemp, and Hexerei plants more accessible in the Market
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/seeds_for_emerald.json
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/seeds_for_gold.json
Labels: Enhancement

#308 Update CHANGELOG.md
  changelogs/CHANGELOG.md
Labels: Development

#310 EE Expert Integration
  changelogs/CHANGELOG.md
  config/configswapper/expert/serverconfig/immersiveengineering-server.toml
  config/configswapper/normal/serverconfig/immersiveengineering-server.toml
  kubejs/assets/emendatusenigmatica/lang/en_us.json
  kubejs/client_scripts/lang_modifications.js
  kubejs/data/farmingforblockheads/farmingforblockheads_compat/seeds_for_gold.json
  kubejs/server_scripts/expert/recipes/ars_nouveau/imbuement.js
  kubejs/server_scripts/expert/recipes/create/mixing.js
  kubejs/server_scripts/expert/recipes/enigmatica/crushing_tiers.js
  kubejs/server_scripts/expert/recipes/hexerei/pestle_and_mortar.js
  kubejs/server_scripts/expert/recipes/mekanism/purifying.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/thermo_plant.js
  kubejs/server_scripts/expert/recipes/thermal/smelter.js
Labels: Development

#311 Expert metalworking
  MODLIST.md
  config/almostunified/unify.json
  kubejs/server_scripts/base/recipes/create/pressing.js
  kubejs/server_scripts/base/recipes/createaddition/rolling.js
  kubejs/server_scripts/base/recipes/immersiveengineering/metalpress.js
  kubejs/server_scripts/base/recipes/thermal/press.js
  kubejs/server_scripts/base/tags/items/thermal/casts.js
  kubejs/server_scripts/constants/metal_properties.js
  kubejs/server_scripts/constants/wood_properties.js
  kubejs/server_scripts/expert/recipes/create/sequenced_assembly.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/normal/recipes/create/crushing.js
  kubejs/server_scripts/normal/recipes/create/pressing.js
  kubejs/server_scripts/normal/recipes/create/splashing.js
  kubejs/server_scripts/normal/unification/unify_dust_processing.js
Labels: Development

#317 Expert Integrations
  kubejs/client_scripts/base/tooltips.js
  kubejs/client_scripts/constants/jei_hidden_disabled.js
  kubejs/data/twilightforest/stalactites/entries/aluminium_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/coal_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/copper_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/diamond_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/emerald_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/gold_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/iron_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/lapis_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/lead_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/nickel_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/osmium_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/redstone_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/silver_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/tin_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/entries/uranium_ore_stalactite.json
  kubejs/data/twilightforest/stalactites/large_hollow_hill.json
  kubejs/data/twilightforest/stalactites/medium_hollow_hill.json
  kubejs/data/twilightforest/stalactites/small_hollow_hill.json
  kubejs/server_scripts/base/recipes/twilightforest/stalactites.js
  kubejs/server_scripts/expert/recipes/ars_nouveau/enchanting_apparatus.js
  kubejs/server_scripts/expert/recipes/compactmachines/shaped.js
  kubejs/server_scripts/expert/recipes/enigmatica/remove.js
  kubejs/server_scripts/expert/recipes/entangled/shaped.js
  kubejs/server_scripts/expert/recipes/functionalstorage/shaped.js
  kubejs/server_scripts/expert/recipes/mekanism/metallurgic_infusing.js
  kubejs/server_scripts/expert/recipes/naturesaura/tree_ritual.js
  kubejs/server_scripts/expert/recipes/pneumaticcraft/pressure_chamber.js
  kubejs/server_scripts/expert/recipes/sophisticatedstorage/shaped.js
  kubejs/server_scripts/expert/recipes/twilightforest/hollow_hills.js
  kubejs/server_scripts/normal/recipes/thermal/centrifuge.js
  kubejs/server_scripts/normal/recipes/twilightforest/hollow_hills.js
Labels: Development

#319 Set up Blacklist for Building Gadgets
  kubejs/server_scripts/base/tags/blocks/buildinggadgets/blacklists.js
Labels: Enhancement

#320 Update Storage Quests to reference the containers tag rather than the storage tag
  config/ftbquests/quests/chapters/storage.snbt
Labels: Enhancement

#325 Unify More Loot!
  kubejs/server_scripts/base/unification/unify_loot.js
Labels: Bug
